version: 2
updates:
- package-ecosystem: npm
  versioning-strategy: increase
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "19:00"
  groups:
    storybook:
      patterns:
        - "@storybook/*"
        - storybook
        - "@chromatic-com/storybook"
        - "@whitespace/storybook-addon-html"
        - "chromatic"
    eslint:
      patterns:
        - "eslint*"
        - "@stylistic/eslint-plugin-js"
        - "esbuild-plugin-eslint"
    stylelint:
      patterns:
        - "stylelint*"
    esbuild:
      patterns:
        - "esbuild*"
    babel:
      patterns:
        - "@babel*"
    webpack:
      patterns:
        - "webpack*"
  open-pull-requests-limit: 10
  reviewers:
  - qld-gov-au/qld-online-dev-team
