# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM  Package

on:
  push:
  #On versioned releases
    tags:
      - v*.*.*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      force:
        type: choice
        description: Retry Publish Version
        options:
          - No
          - Yes

jobs:
  build:
    if: github.repository == 'qld-gov-au/qgds-vanilla' #lock npmjs deployment to single repo, alter if you change package.json
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node: [ '22' ]
    name: Lint, Test, Build and Deploy on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v5

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install #run on lint step (Which is cached)
        run: | # Install packages per package-lock.json only
          npm ci

      - name: Lint
        run: |
          echo "lint disabled at this time" #npm run lint

      - name: Test
        run: |
          npm run test

      - name: Build 🔧
        run: | # build the files
          npm run build

  publish-npm:
    needs: build
    env:
      HAVE_DEPLOY_KEY: ${{ github.repository == 'qld-gov-au/qgds-vanilla' }}
      #When run on push tags, force is '', default for workflow_dispatch is No so you can't trigger without a double action
      WORKFLOW_DEPLOYMENT: ${{ github.event_name != 'workflow_dispatch'  || github.event.inputs.force == 'Yes' }}
      DO_DEPLOYMENT: ${{ github.repository == 'qld-gov-au/qgds-vanilla' && ( github.event_name != 'workflow_dispatch'  || github.event.inputs.force == 'Yes' ) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Required for OIDC
    environment:
      name: npmjs
      url: https://www.npmjs.com/package/@qld-gov-au/qgds-vanilla
    steps:
      - uses: actions/checkout@v5

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          scope: '@qld-gov-au'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - run: npm ci

      - name: Build 🔧
        run: | # build the files
          npm run build

#      - name: "Update package scope, export package name"
#        id: package_details
#        run: |
#          echo "replacing npm scope to repo owner GITHUB_REPOSITORY_OWNER = $GITHUB_REPOSITORY_OWNER"
#          temp_file=$(mktemp)
#          package=${GITHUB_REPOSITORY_OWNER,,}
#          awk -v scope="$package" '{
#                if ($0 ~ /"name": "@[a-zA-Z0-9_-]+\//) {
#                    sub(/@[a-zA-Z0-9_-]+\//, "@" scope "/")
#              }
#                print
#            }'  package.json > "$temp_file" && mv "$temp_file" package.json
#          echo "package.json updated"
#          cat package.json
#          echo "package=`npm pkg get name`" >> $GITHUB_STATE
#
#      - uses: tobysmith568/npm-publish-latest-tag@v1
#        id: latest_tag
#        with:
#          package-json: ./package.json

      - name: Publish
        if: ${{ env.DO_DEPLOYMENT == 'true' }}
        run: |
            npm publish --provenance --access=public

      - name: NPM Publish - Is Skipped
        if: ${{ env.HAVE_DEPLOY_KEY != 'true' }}
        run: |
            echo "## This is a fork" >> $GITHUB_STEP_SUMMARY
            echo "If you wish to publish to npmjs.org. Please change package prefix name and update this file to new repo location."  >> $GITHUB_STEP_SUMMARY

      - name: Publish - Skipped
        if: ${{ env.DO_DEPLOYMENT != 'true' }}
        run: |
          echo "### Publish skipped" >> $GITHUB_STEP_SUMMARY
          echo "DO_DEPLOYMENT: github.event_name: ${{ github.event_name != 'workflow_dispatch'}} || github.event.inputs.force: ${{ github.event.inputs.force == 'Yes' }}"  >> $GITHUB_STEP_SUMMARY

